### ISSUE TITLE
Monkey Patch breaks latest Visual Code Insiders version

### ISSUE THREAD

**Issue by Hanif1601** [iocave/monkey-patch#15]
After updating to 1.48.0 and re-apply the patch, Visual Code suddenly won't open and boned. When I opened the app from Command Prompt, here's I got:

`TypeError: bootstrap.uriFromPath is not a function
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:1012:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1049:10)
    at Module.load (internal/modules/cjs/loader.js:860:32)
    at Module._load (internal/modules/cjs/loader.js:772:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:897:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at startup (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\main.js:8:1)
    at onReady (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\main.js:8:247)`

This probably an newest or recent issue on newest version of Monkey Patch because Visual Code doesn't want to open and shows the Bootstrap error. Hopefully it'll fixed soon.

**Comment by knopp** [comment]
Duplicate https://github.com/iocave/monkey-patch/issues/14
